image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

install:
  - pip install -e .
  - pip install pytest

build: off

test_script:
  - python --version
  - py.test
