image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

install:
  - "%PYTHON%\\python.exe -m pip install -U wheel pip"
  - "%PYTHON%\\python.exe -m pip install -e ."
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe --version"
  - "build.cmd %PYTHON%\\python.exe -m pytest"
