language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install --no-cache-dir -e .
  - pip install -r dev-requirements.txt
  - pip install --no-cache-dir codecov
  - pip install --no-cache-dir pytest-cov~=2.8
  - pip install --no-cache-dir pytest
script:
  - flake8
  - pytest --cov=iottalkpy/
after_success:
  - codecov
notifications:
  email: false
