language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --no-cache-dir -e .
  - pip install --no-cache-dir codecov
  - pip install --no-cache-dir pytest pytest-cov~=2.8
script:
  - pytest --cov=iottalkpy/
after_success:
  - codecov
notifications:
  email: false
