language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - pytest --cov=iottalkpy/
after_success:
  - codecov
notifications:
  email: false
